spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/staffgaugesurvey?serverTimezone=UTC
    username: root
    password: 282818
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath*:com/staffGauge/survey/user/dal/persistence/*.xml"
  type-aliases-package: com.staffGauge.survey.user.dao

dubbo:
  application:
    name: cargo-service
    owner: Fu
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: zookeeper://192.168.1.142:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://192.168.1.142:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    base-packages: com.staffGauge.survey.cargo.serverImpl

