thrift:
  ip: ${thrift_ip}
  port: 8000
server:
  port: 8085
dubbo:
  application:
    name: cargo-server
    owner: Fu
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: zookeeper://${zookeeper_ip}:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://${zookeeper_ip}:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB