spring:
  datasource:
    url: jdbc:mysql://localhost:3306/staffgaugesurvey?serverTimezone=UTC
    cargoname: root
    password: 282818
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      additional-paths: /mapper-[\\w-\\.]+jar , /pagehelper-[\\w-\\.]+jar
mybatis:
  mapper-locations: classpath*:com/staffGauge/survey/cargo/dal/persistence/*.xml"
  #  type-aliases-package: com.staffGauge.survey.cargo.dao
  type-aliases-package: com.staffGauge.survey.cargo.dao
mapper:
  mappers:
    - tk.mybatis.springboot.util.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
dubbo:
  application:
    name: cargo-service
    owner: Fu
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: zookeeper://192.168.0.103:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://192.168.0.103:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    base-packages: com.staffGauge.survey.cargo.serverImpl

