dubbo:
  application:
    name: user-server
    owner: Fu
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://${zookeeper_ip}:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://${zookeeper_ip}:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
logging:
  config:
    classpath: logback.xml
server:
  port: 8083

spring:
  redis:
    host: 192.168.121.130
    port: 6379
    timeout: 3000
    database: 0
  mail:
    host: smtp.qq.com
    username: 2067384295@qq.com
    password: yrwrctisajzdfaje # 授权码
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    default-encoding: utf-8
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB


##邮箱服务器地址
#QQ smtp.qq.com
##sina smtp.sina.cn
##aliyun smtp.aliyun.com
##163 smtp.163.com

