apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service
  name: user-service
  namespace: default
spec:
  ports:
    - name: user-edge-service-port
      port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app: user-service
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-server
          image: registry.cn-hangzhou.aliyuncs.com/cargo_docker/cargo:user-server
          ports:
            - containerPort: 8083
        - name: user-provider
          image: registry.cn-hangzhou.aliyuncs.com/cargo_docker/cargo:user-provider
          ports:
            - containerPort: 20880

